### ISSUE TITLE
DMRGateway doesn't respond to SIGTERM if waiting for MMDVMHost to connect

### ISSUE THREAD

**Issue by marrold** [g4klx/DMRGateway#10]
I am trying to create a systemd script to start and stop DMRGateway.

In doing so, I have discovered that DMRGateway doesn't respond to SIGTERM if it's waiting for MMDVMHost to connect.

Thanks

**Comment by g0wfv** [comment]
Replicated issue independantly on two separate installs here also.

**Comment by g4klx** [comment]
Do a new pull, it should behave better now.

**Comment by marrold** [comment]
All sorted, thanks Jonathan.
