### ISSUE TITLE
DMRA Frame Format

### ISSUE THREAD

**Issue by marrold** [g4klx/DMRGateway#100]
Hi Jonathan, I've encountered an issue with parsing DMRA Talker Alias frames in hblink3 - https://github.com/HBLink-org/hblink3/issues/8

If possible please could you confirm the structure of a DMRA frame?

Thanks

**Comment by g4klx** [comment]
Hi Matthew
As far as I can tell, it’s like this:

The format of the DMRA message is:

Number of bytes  Description

4                'DMRA' in ASCII

3                The DMR Id of the repeater, MSB first.

1                The type of the following TA data, 0 for the header, 1 for block 1, 2 for block 2, 3 for block 3.

7                The TA data, the 56 bits described in sections 7.1.1.4, 7.1.1.5, 7.2.18 and 7.2.19 of ETSI TS 102 361-2V2.4.1 (2017-10).

The data can be in many formats potentially, not just ASCII.
Jonathan G4KLX 

Sent from Yahoo Mail for iPhone


On Friday, January 15, 2021, 14:41, Matthew Harrold <notifications@github.com> wrote:




Hi Jonathan, I've encountered an issue with parsing DMRA Talker Alias frames in hblink3 - HBLink-org/hblink3#8

If possible please could you confirm the structure of a DMRA frame?

Thanks

**Comment by marrold** [comment]
Thought I'd already replied to this one - Thanks for the info
