### ISSUE TITLE
TA not showing

### ISSUE THREAD

**Issue by faxe2110** [g4klx/DMRGateway#14]
I´m using 
MMDVMHost by G4KLX Version: 20170501 GitID #ed93628
and 
DMRGateway-20170522 GitID #f90dbb5
It is not possible for me to become the TA on the display of my PD785.  
When I just running the MMDVMHost without the DMRGateway, that means go to the mmdvm.ini and switch the 127.0.0.1 for the GW to the DMR Master Server IP, all is running fine and the TA is showing on display.
Is that a known issue?? 

SA7BNT / Tim

**Comment by g4klx** [comment]
TA and Embedded GPS don't pass through the gateway at the moment.

**Comment by DL4OCH** [comment]
Are there any plans to enable TA and GPS with mapped TG's ?

**Comment by g4klx** [comment]
One day. It isn't trivial to do though, and I don't have a lot of free time :-( Considering that TA causes most DMR radios to not work properly, I didn't consider it a high priority.
