### ISSUE TITLE
Private Call passing through DMRGateway

### ISSUE THREAD

**Issue by oe1kbc** [g4klx/DMRGateway#22]
We run DMRGateway and MMDVMHost Vienna last versions and all three NET connections working very well. We use XLX/TG8 & BM/TG2321-2329 & DMR+ PassAll

Private Calls and text Messages not passing to DMR+ server

Is it posible to get this streams?

Kurt
OE1KBC

**Comment by g4klx** [comment]
Hi Kurt

It should work.

You need to get the latest DMRGateway from GitHub as there was an important fix in it for PassAll. If it still doesn't work then you'll have to put the RuleTrace on and see what is happening.

**Comment by oe1kbc** [comment]
Hi Jonathan,
Thank you for "Rule Trace" hint.
I forgott on DMR-2 (DMR+)
PassAllPC=1
PassAllPC=2

Kurt
