### ISSUE TITLE
Fail to make DMRGateway.cpp

### ISSUE THREAD

**Issue by firefigther** [g4klx/DMRGateway#26]
pi@raspberrypi:/opt/DMRGateway $ sudo make 
echo "const char *gitversion = \"bee2f211848011690a71153fff0ef8f11e189388\";" > GitVersion.h
g++ -g -O3 -Wall -std=c++0x -pthread -c -o BPTC19696.o BPTC19696.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o Conf.o Conf.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o CRC.o CRC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRData.o DMRData.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMREmbeddedData.o DMREmbeddedData.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMREMB.o DMREMB.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRFullLC.o DMRFullLC.cpp
g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRGateway.o DMRGateway.cpp
DMRGateway.cpp: In member function \u2018int CDMRGateway::run()\u2019:
DMRGateway.cpp:475:17: warning: unused variable \u2018srcId\u2019 [-Wunused-variable]
    unsigned int srcId = data.getSrcId();
                 ^
DMRGateway.cpp:491:16: error: \u2018dstId\u2019 was not declared in this scope
    } else if ((dstId <= (m_xlx1Base + 26U) || dstId == (m_xlx1Base + 1000U)) && flco == FLCO_USER_USER && slotNo == m_xlx1Slot && dstId >= m_xlx1Base) {
                ^
DMRGateway.cpp:491:81: error: \u2018flco\u2019 was not declared in this scope
    } else if ((dstId <= (m_xlx1Base + 26U) || dstId == (m_xlx1Base + 1000U)) && flco == FLCO_USER_USER && slotNo == m_xlx1Slot && dstId >= m_xlx1Base) {
                                                                                 ^
DMRGateway.cpp:491:107: error: \u2018slotNo\u2019 was not declared in this scope
    } else if ((dstId <= (m_xlx1Base + 26U) || dstId == (m_xlx1Base + 1000U)) && flco == FLCO_USER_USER && slotNo == m_xlx1Slot && dstId >= m_xlx1Base) {
                                                                                                           ^
DMRGateway.cpp:505:21: error: \u2018srcId\u2019 was not declared in this scope
        writeXLXLink(srcId, 4000U, m_xlxNetwork1);
                     ^
DMRGateway.cpp:511:20: error: \u2018srcId\u2019 was not declared in this scope
       writeXLXLink(srcId, dstId, m_xlxNetwork1);
                    ^
DMRGateway.cpp:547:21: error: \u2018srcId\u2019 was not declared in this scope
        writeXLXLink(srcId, 4000U, m_xlxNetwork2);
                     ^
DMRGateway.cpp:553:20: error: \u2018srcId\u2019 was not declared in this scope
       writeXLXLink(srcId, dstId, m_xlxNetwork2);
                    ^
DMRGateway.cpp:679:30: error: \u2018data\u2019 was not declared in this scope
    ret = m_xlxNetwork1->read(data);
                              ^
DMRGateway.cpp:698:30: error: \u2018data\u2019 was not declared in this scope
    ret = m_xlxNetwork2->read(data);
                              ^
DMRGateway.cpp:718:30: error: \u2018data\u2019 was not declared in this scope
    ret = m_dmrNetwork1->read(data);
                              ^
DMRGateway.cpp:763:30: error: \u2018data\u2019 was not declared in this scope
    ret = m_dmrNetwork2->read(data);
                              ^
DMRGateway.cpp:833:23: error: \u2018data\u2019 was not declared in this scope
    ret = voice1->read(data);
                       ^
DMRGateway.cpp:842:23: error: \u2018data\u2019 was not declared in this scope
    ret = voice2->read(data);
                       ^
DMRGateway.cpp: At global scope:
DMRGateway.cpp:885:2: error: expected unqualified-id before \u2018delete\u2019
  delete voice1;
  ^
DMRGateway.cpp:886:2: error: expected unqualified-id before \u2018delete\u2019
  delete voice2;
  ^
DMRGateway.cpp:888:2: error: \u2018m_repeater\u2019 does not name a type
  m_repeater->close();
  ^
DMRGateway.cpp:889:2: error: expected unqualified-id before \u2018delete\u2019
  delete m_repeater;
  ^
DMRGateway.cpp:891:2: error: expected unqualified-id before \u2018if\u2019
  if (m_dmrNetwork1 != NULL) {
  ^
DMRGateway.cpp:896:2: error: expected unqualified-id before \u2018if\u2019
  if (m_dmrNetwork2 != NULL) {
  ^
DMRGateway.cpp:901:2: error: expected unqualified-id before \u2018if\u2019
  if (m_xlxNetwork1 != NULL) {
  ^
DMRGateway.cpp:906:2: error: expected unqualified-id before \u2018if\u2019
  if (m_xlxNetwork2 != NULL) {
  ^
DMRGateway.cpp:911:2: error: expected unqualified-id before \u2018delete\u2019
  delete timer[1U];
  ^
DMRGateway.cpp:912:2: error: expected unqualified-id before \u2018delete\u2019
  delete timer[2U];
  ^
DMRGateway.cpp:914:2: error: expected unqualified-id before \u2018return\u2019
  return 0;
  ^
DMRGateway.cpp:915:1: error: expected declaration before \u2018}\u2019 token
 }
 ^
DMRGateway.cpp: In member function \u2018int CDMRGateway::run()\u2019:
DMRGateway.cpp:883:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
Makefile:17: die Regel für Ziel \u201eDMRGateway.o\u201c scheiterte
make: *** [DMRGateway.o] Fehler 1

**Comment by phl0** [comment]
Fix is underway ...

**Comment by firefigther** [comment]
Thanks to all

Uli
