### ISSUE TITLE
Busy indicator

### ISSUE THREAD

**Issue by cyanide-burnout** [g4klx/DMRGateway#35]
Please add new measage to indicate that repeater is busy by call of another network or mode. It is required to make proper handle of locks and routes. It could be optimistic locking model where host responds with busy signal when master sends MO stream.

**Comment by cyanide-burnout** [comment]
P.S. DMR homebrew proto

**Comment by cyanide-burnout** [comment]
It might me something like RPTB and one byte bitset:
DMO slot busy, slot 1 busy, slot 2 busy, busy by other mode

**Comment by faxe2110** [comment]
Great idea, but wrong place to post it. DMRGateway just using one mode. Just to let me know, we are talking about DMR in DMRGateway. If i´m wrong please let me know. Always nice to learn new things about the digital modes. Busy by other mode is a lovely idea from you, but maybe it will be better placed in MMDVMHost. There we talking YSF, DMR and D-Star (busy by other mode).

**Comment by cyanide-burnout** [comment]
Yep, you are right about MMDVM host. But in my opinion it should be implemented in both.

**Comment by faxe2110** [comment]
Hmmmm, how should it be implemented in both (MMDVMHost & DMRGateway) if the DMRGateway only use one mode (digital mobile radio standard)?? Please explain that so we maybe can follow you what you are thinking about.

**Comment by cyanide-burnout** [comment]
1) Indication when MMDVMHost is busy by other mode like D-STAR, Fusion, P.25
2) Indication when DMRGateway is busy by call of other network like XLXD, BM or IPSC2

**Comment by cyanide-burnout** [comment]
What is wrong with this request? Why it is closed?
