### ISSUE TITLE
XLX 1 and 2 with StartUp

### ISSUE THREAD

**Issue by pjao** [g4klx/DMRGateway#37]
Hi all!

I was doing some tests, and needed to configure both networks XLX1 and XLX2 with StartUp options turned on.

The result was many lines with "overflow in the DMR slot RF queue" since the autoconnect was started at same time, and the "voice" come at the same time.

It will be nice to have some king of delay or the system do not send the connection information at the same time.

73's
Paulo - CT2JAY

**Comment by phl0** [comment]
The XLX stuff is being worked on anyway: https://github.com/g4klx/DMRGateway/tree/XLXs

**Comment by pjao** [comment]
Nice, I'm testing it right now.

One question about this branch XLXs, how can we change the XLX Number on the air?

**Comment by g4klx** [comment]
The number is 4000 on from the link requests. By this I mean:

If on your system 4005 links you to XLXnnnE then 8950 will link you to XLX950 with the specified default reflector in the XLXHosts.txt file.
If you have 64005 to link to XLXnnnE then 68950 will link you to XLX950, etc.
