### ISSUE TITLE
Enable DMRGateway to disable providing GEO-position of repeater to specified DMR-network

### ISSUE THREAD

**Issue by dg9vh** [g4klx/DMRGateway#38]
Hi Jonathan,

as you can find at DF2ET's branch at https://github.com/phl0/DMRGateway/tree/schwitchAPRSonOrOff there is a version that enables the DMRGateway to suppress provisioning of the GEO-position of a repeater into a specified DMR-network.

Since BrandMeister now also starts providing geo-positions to aprs.fi we now have the real problem of bouncing repeaters because of different position reports and also reporting repeaters as being a part of a network (completely) but only providing specific features of this network.

So It would be a bonus for all using the DMRGateway to avoid such problems in future if we could merge Flo's developments into the main-branch.

I would ask the repeater-keepers in the corresponding yahoo-groups to sign here with a comment or to send me an email to build up a list of person with interrest to show you, that it is not only a few, that are showing interrest in this.

best 73
Kim
DG9VH

**Comment by electrigga** [comment]
A switch for every network - this would be a great feature!

**Comment by dg9vh** [comment]
@electrigga for each DMR-Network transporting the data a switch to disable it is build in.

**Comment by ve1aic** [comment]
Up until 3 days ago the beacon below was sent from a DMR+ server but not from my info.
The callsign, freq is correct but location is off by 15km so was not produced by me.
I also send APRS beacons from YSFGateway and ircDDBgateway but nothing from BM Network that I know of.

APRS station VE1CRA
Comment:     IPSC DR3000 443.3000MHz
Location:     46°15.99' N 63°07.17' W - locator FN86KG53PX

Last position:     2017-09-12 16:49:00 ADT (3d 30m ago)
2017-09-12 16:49:00 ADT local time at Charlottetown, Canada [?]
Device:     Jonathan, G4KLX: ircDDB Gateway (D-Star)
Last path:     VE1CRA>APDG02 via TCPIP*,qAU,DMRAPRS

**Comment by faxe2110** [comment]
@ve1aic you may have a look @ this
http://news.brandmeister.network/brandmeister-repeater-path-added-in-the-digipath-field-of-aprs-packet/#more-150

SA7BNT
Tim

**Comment by DL4OCH** [comment]
This would be great feature!
I could provide my favorite network my geo-location and can keep DMR+ out of it, as they show my repeater asa fully member of their network.

DL4OCH, SysOp of DB0EIG

**Comment by dg9vh** [comment]
closed with https://github.com/g4klx/DMRGateway/commit/9289d48939b8fbe8a2ead979d69c458603b759f2
