### ISSUE TITLE
Warning with compile

### ISSUE THREAD

**Issue by pjao** [g4klx/DMRGateway#39]
After last update, warning when compiling. Variables?

![imagem](https://user-images.githubusercontent.com/6640329/30513926-f6fe7a94-9b03-11e7-9093-0245d8f157c7.png)

**Comment by g4klx** [comment]
It should be fixed now.

**Comment by pjao** [comment]
Fixed (https://github.com/g4klx/DMRGateway/commit/acc562381e40315959cacd59e3bb8079bcaa5f2d) closing issue
