### ISSUE TITLE
Different ID's for the different Networks

### ISSUE THREAD

**Issue by dc7jzb** [g4klx/DMRGateway#54]
Is there a way for a function, to take different DMR-ID's for the different Networks ?
The Background is, that Brandmeister can work with "Testing-ID's" DMR-ID+<00-99>, but all other Networks didn't accept them.

When you Test a Repeater or Hotspot with one of these ID's you only can take Brandmeister and not the other Networks inside the Gateway. Or you want to Monitor two Reflectors of the same Network at the same Time wirhout switching between them

73 de Mario, DC7JZB

**Comment by g4klx** [comment]
Yes, you can set a different id per network. Just add an Id=NNNN line in the network section that you wish to override.

**Comment by dc7jzb** [comment]
Sorry, forgot to Close.
Works fine, tnx.
