### ISSUE TITLE
Vocal beacon

### ISSUE THREAD

**Issue by Emamisu** [g4klx/DMRGateway#6]
Hi Jonathan, 
is possible to have a vocal beacon like the CW ID in MMDVMHost? 

Ciao
Emanuele

**Comment by Emamisu** [comment]
A custom vocal beacon recorded in .ambe by the sysop.

**Comment by g4klx** [comment]
And how would that work? If it was on slot 1, you wouldn't hear it on slot 2, if it was TG9 you wouldn't hear it on any other TG. It can work on D-Star, YSF and P25 but not DMR.

**Comment by Emamisu** [comment]
Almost all users use the promisquous mode on Chinese terminals. On Hytera and Motorola many use to have all the tg in the rx list, so the beacon can be heard almost by all users by inserting it for example on tg9. The beacon could be transmitted on both slots at the same time. It's possible?

**Comment by g0wfv** [comment]
No promiscuous mode on CS700!

**Comment by g0wfv** [comment]
Having said that, if it's configurable to any TG, most radios have a group receive function whereby a range of TGs can be rx'd regardless of the current Tx TG ...

... and having said *THAT*, there's still no guarantee folks will use it so no guarantee it will be rx'd.

Too many variables that will nullify its existence.

**Comment by g4klx** [comment]
It's a very silly idea on DMR. Closing this issue.

**Comment by g0wfv** [comment]
Just playing Satan's Solicitor ;-)
