### ISSUE TITLE
SrcRewrite for route another network

### ISSUE THREAD

**Issue by d51r3verse** [g4klx/DMRGateway#74]
I am testing SrcRewrite/TypeRewrite for relay use.
Tested with private call echo contacts. everytime I PPT, automatically change echo contacts.
HT received another network's TG# wrapped private calls, but I PPT that messages... rule trace RF->NET, after that... network activity nothing.

[DMR Network 1]
#Local=62051	#If I change it to same port, both server connections unstables
TypeRewrite0=2,11440991,2,440991	#TG11440991 -> PC440991
TypeRewrite1=2,11440997,2,440997	#TG11440997 -> PC440997
#SrcRewrite0=2,440991,2,11440997,1	#PC440991 -> TG11440997		#Internal echo relay loop works well
SrcRewrite1=2,440997,2,13009990,1	#PC440997 -> TG1300990@NET3 #NOT WORKING

[DMR Network 3]
#Local=62053
TypeRewrite0=2,13000100,2,100	#TG13000100 -> PC100
TypeRewrite1=2,13009990,2,9990	#TG13009990 -> PC9990
SrcRewrite0=2,100,2,13009990,1	#PC100 -> TG13009990
SrcRewrite1=2,9990,2,13000100,1	#RECEIVES

I: 2019-03-04 22:56:12.382 Rule trace: yes
I: 2019-03-04 22:56:12.383 DMR Network 1 Parameters
I: 2019-03-04 22:56:12.383     Name: NET1
I: 2019-03-04 22:56:12.383     Id: MYID
I: 2019-03-04 22:56:12.383     Address: 150.66.42.231
I: 2019-03-04 22:56:12.383     Port: 62031
I: 2019-03-04 22:56:12.383     Local: random
I: 2019-03-04 22:56:12.383     Location Data: yes
M: 2019-03-04 22:56:12.383 NET1, Opening DMR Network
I: 2019-03-04 22:56:12.383     Rewrite RF: 2:TG9 -> 2:TG9
I: 2019-03-04 22:56:12.383     Rewrite Net: 2:TG9 -> 2:TG9
I: 2019-03-04 22:56:12.383     Rewrite RF: 2:94000-95000 -> 2:4000-5000
I: 2019-03-04 22:56:12.384     Rewrite RF: 2:TG11440991 -> 2:440991
I: 2019-03-04 22:56:12.384     Rewrite RF: 2:TG11440997 -> 2:440997
I: 2019-03-04 22:56:12.384     Rewrite Net: 2:4000-5000 -> 2:TG9
I: 2019-03-04 22:56:12.384     Rewrite Net: 2:440991 -> 2:TG11440997
I: 2019-03-04 22:56:12.384     Rewrite Net: 2:440997 -> 2:TG13009990
I: 2019-03-04 22:56:12.384 DMR Network 3 Parameters
I: 2019-03-04 22:56:12.384     Name: NET3
I: 2019-03-04 22:56:12.384     Id: MYID
I: 2019-03-04 22:56:12.384     Address: NET3
I: 2019-03-04 22:56:12.395     Port: 62031
I: 2019-03-04 22:56:12.395     Local: random
I: 2019-03-04 22:56:12.395     Location Data: no
I: 2019-03-04 22:56:13.028     Options: StartRef=4000; RelinkTime=11; UserLink=1;
M: 2019-03-04 22:56:13.029 NET3, Opening DMR Network
I: 2019-03-04 22:56:13.029     Rewrite RF: 2:TG13000100 -> 2:100
I: 2019-03-04 22:56:13.029     Rewrite RF: 2:TG13009990 -> 2:9990
I: 2019-03-04 22:56:13.029     Rewrite Net: 2:100 -> 2:TG13009990
I: 2019-03-04 22:56:13.029     Rewrite Net: 2:9990 -> 2:TG11440991
M: 2019-03-04 22:56:13.029 DMRGateway-20190130_Pi-Star_v4 is running

* How about change rewrite rules processing orders?
-Conflicting(mutual exclusion required) with TGRewrite
As is: RewriteTG -> RewritePC -> RewriteType -> RewriteSrc -> PassAllTG -> PassAllPC

I can not use this simple TGRewrite rules......
TypeRewrite0=2,13000100,2,100	#TG13000100 -> PC100
TypeRewrite1=2,13009990,2,9990	#TG13009990 -> PC9990
SrcRewrite0=2,100,2,13009990,1	#PC100 -> TG13009990
SrcRewrite1=2,9990,2,13000100,1	#RECEIVES
TGRewrite0=1,13000001,1,1,999999
TGRewrite1=2,13000001,2,1,999999
PCRewrite0=2,13000001,2,1,999999
PCRewrite0=1,13000001,1,1,999999

To be: RewriteType -> RewriteSrc -> RewritePC -> RewriteTG -> PassAllTG -> PassAllPC

**Comment by g4klx** [comment]
I don't understand what you are trying to do. I do not think that the idea of stacking rewrite rules is very good, it can lead to loops and confusion. I would think that what you are trying to achieve can be done more simply, or maybe totally rethink your solution.

**Comment by d51r3verse** [comment]
Thanks, but don't know why DMRGateway does not properly route my last calls?(network 3 transmission)
D: 2019-03-04 22:27:23.439 Rule Trace, RF transmission: Slot=2 Src=MYID Dst=TG11440991
D: 2019-03-04 22:27:23.439 Rule Trace,	RewriteTG from NET1 Slot=2 Dst=TG9: not matched
D: 2019-03-04 22:27:23.439 Rule Trace,	RewritePC from NET1 Slot=2 Dst=94000-95000: not matched
D: 2019-03-04 22:27:23.439 Rule Trace,	RewritePC from NET1 Slot=2 Dst=11000001-11999999: not matched
D: 2019-03-04 22:27:23.439 Rule Trace,	RewritePC from NET1 Slot=1 Dst=11000001-11999999: not matched
D: 2019-03-04 22:27:23.439 Rule Trace,	RewriteType NET1 Slot=2 Dst=TG11440991: matched
D: 2019-03-04 22:27:29.132 Rule Trace, network 1 transmission: Slot=2 Src=440991 Dst=MYID
D: 2019-03-04 22:27:29.132 Rule Trace,	RewriteTG from NET1 Slot=2 Dst=TG9: not matched
D: 2019-03-04 22:27:29.132 Rule Trace,	RewriteSrc from NET1 Slot=2 Src=4000-5000: not matched
D: 2019-03-04 22:27:29.133 Rule Trace,	RewriteSrc from NET1 Slot=2 Src=440991-440991: matched
D: 2019-03-04 22:27:29.133 Rule Trace,	RewriteSrc to NET1 Slot=2 Dst=TG11440997
D: 2019-03-04 22:27:32.679 Rule Trace, RF transmission: Slot=2 Src=MYID Dst=TG11440997
D: 2019-03-04 22:27:32.679 Rule Trace,	RewriteTG from NET1 Slot=2 Dst=TG9: not matched
D: 2019-03-04 22:27:32.679 Rule Trace,	RewritePC from NET1 Slot=2 Dst=94000-95000: not matched
D: 2019-03-04 22:27:32.679 Rule Trace,	RewritePC from NET1 Slot=2 Dst=11000001-11999999: not matched
D: 2019-03-04 22:27:32.679 Rule Trace,	RewritePC from NET1 Slot=1 Dst=11000001-11999999: not matched
D: 2019-03-04 22:27:32.679 Rule Trace,	RewriteType NET1 Slot=2 Dst=TG11440991: not matched
D: 2019-03-04 22:27:32.679 Rule Trace,	RewriteType NET1 Slot=2 Dst=TG11440997: matched
D: 2019-03-04 22:27:38.089 Rule Trace, network 1 transmission: Slot=2 Src=440997 Dst=MYID
D: 2019-03-04 22:27:38.089 Rule Trace,	RewriteTG from NET1 Slot=2 Dst=TG9: not matched
D: 2019-03-04 22:27:38.089 Rule Trace,	RewriteSrc from NET1 Slot=2 Src=4000-5000: not matched
D: 2019-03-04 22:27:38.089 Rule Trace,	RewriteSrc from NET1 Slot=2 Src=440991-440991: not matched
D: 2019-03-04 22:27:38.090 Rule Trace,	RewriteSrc from NET1 Slot=2 Src=440997-440997: matched
D: 2019-03-04 22:27:38.090 Rule Trace,	RewriteSrc to NET1 Slot=2 Dst=TG13000100		<-- NET#1 PRIAVTECALL RESPONSE WRAPPED WITH NET#3's TGID
D: 2019-03-04 22:27:41.674 Rule Trace, RF transmission: Slot=2 Src=MYID Dst=TG13000100
D: 2019-03-04 22:27:41.675 Rule Trace,	RewriteTG from NET1 Slot=2 Dst=TG9: not matched
D: 2019-03-04 22:27:41.675 Rule Trace,	RewritePC from NET1 Slot=2 Dst=94000-95000: not matched
D: 2019-03-04 22:27:41.675 Rule Trace,	RewritePC from NET1 Slot=2 Dst=11000001-11999999: not matched
D: 2019-03-04 22:27:41.675 Rule Trace,	RewritePC from NET1 Slot=1 Dst=11000001-11999999: not matched
D: 2019-03-04 22:27:41.675 Rule Trace,	RewriteType NET1 Slot=2 Dst=TG11440991: not matched
D: 2019-03-04 22:27:41.675 Rule Trace,	RewriteType NET1 Slot=2 Dst=TG11440997: not matched
D: 2019-03-04 22:27:41.675 Rule Trace,	RewriteTG from NET3 Slot=1 Dst=TG13000101-TG13000299: not matched
D: 2019-03-04 22:27:41.675 Rule Trace,	RewritePC from NET3 Slot=2 Dst=13000001-13999999: not matched
D: 2019-03-04 22:27:41.675 Rule Trace,	RewritePC from NET3 Slot=1 Dst=13000001-13999999: not matched
D: 2019-03-04 22:27:41.675 Rule Trace,	RewriteType NET3 Slot=2 Dst=TG13000100: matched	<-- After then, DMRGateway does not route to NET#3

**Comment by d51r3verse** [comment]
Duplex board's RF -> NET route discard problem solved.
Reason:  Status variable not designed for duplex( TS[1|2].RF[RX|TX|IDLE] or TS[1|2].NET[TX|RX|IDLE] )
Temporal mitigation: Remove condition check before "m_dmrNetwork[1|2|3]->write(data);"
Result: I can send reflector control messages even in congested situations
