### ISSUE TITLE
segfault after last patch...

### ISSUE THREAD

**Issue by dl1bz** [g4klx/DMRGateway#94]
After your last patch (BSD updates) I got a segfault on my debian buster at Pi if I start DMRGateway. Compiling is ok. Segfault is shown if the DMRGateway start the connection to the networks. Disable some networks has no effect, segfault in all cases.

73 Heiko, DL1BZ

**Comment by dl1bz** [comment]
back to commit on Sep 18, 2020 brings the DMRGateway back running here.

73 Heiko, DL1BZ

**Comment by SA7BNT** [comment]
Same here can confirm that. 

73 Tim, SA7BNT

**Comment by dl1bz** [comment]
here is the strace:
mprotect(0x76bb1000, 4096, PROT_READ)   = 0
munmap(0x76fb1000, 49217)               = 0
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 5
connect(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.253.1")}, 16) = 0
poll([{fd=5, events=POLLOUT}], 1, 0)    = 1 ([{fd=5, revents=POLLOUT}])
send(5, "D\f\1\0\0\1\0\0\0\0\0\0\5dmr02\5bzsax\2de\0\0\1\0\1", 32, MSG_NOSIGNAL) = 32
poll([{fd=5, events=POLLIN}], 1, 5000)  = 1 ([{fd=5, revents=POLLIN}])
ioctl(5, FIONREAD, [48])                = 0
recvfrom(5, "D\f\201\200\0\1\0\1\0\0\0\0\5dmr02\5bzsax\2de\0\0\1\0\1"..., 1024, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.253.1")}, [28->16]) = 48
close(5)                                = 0
write(3, "I: 2020-10-06 18:45:40.548 DMR-L"..., 362) = 362
write(1, "I: 2020-10-06 18:45:40.548 DMR-L"..., 362I: 2020-10-06 18:45:40.548 DMR-LL: Original configuration message: DL1BZ   4313875004389875001501+51.1820+14.4317 000Bautzen             Multi-Mode Repeater3http://none
                                                                                               20200606                                MMDVM
) = 362
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x20202020} ---
+++ killed by SIGSEGV +++
Speicherzugriffsfehler
root@HytGW02:/usr/local/src/DMRGateway#

73 Heiko, DL1BZ

**Comment by g4klx** [comment]
If you could compile it for debug, and run it under gdb, that would be very interesting. That would show you (and me) what line it fails at.


Sent from Yahoo Mail for iPhone


On Tuesday, October 6, 2020, 19:48, Heiko <notifications@github.com> wrote:




here is the strace:
mprotect(0x76bb1000, 4096, PROT_READ) = 0
munmap(0x76fb1000, 49217) = 0
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 5
connect(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.253.1")}, 16) = 0
poll([{fd=5, events=POLLOUT}], 1, 0) = 1 ([{fd=5, revents=POLLOUT}])
send(5, "D\f\1\0\0\1\0\0\0\0\0\0\5dmr02\5bzsax\2de\0\0\1\0\1", 32, MSG_NOSIGNAL) = 32
poll([{fd=5, events=POLLIN}], 1, 5000) = 1 ([{fd=5, revents=POLLIN}])
ioctl(5, FIONREAD, [48]) = 0
recvfrom(5, "D\f\201\200\0\1\0\1\0\0\0\0\5dmr02\5bzsax\2de\0\0\1\0\1"..., 1024, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.253.1")}, [28->16]) = 48
close(5) = 0
write(3, "I: 2020-10-06 18:45:40.548 DMR-L"..., 362) = 362
write(1, "I: 2020-10-06 18:45:40.548 DMR-L"..., 362I: 2020-10-06 18:45:40.548 DMR-LL: Original configuration message: DL1BZ 4313875004389875001501+51.1820+14.4317 000Bautzen Multi-Mode Repeater3http://none
20200606 MMDVM
) = 362

--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x20202020} ---
+++ killed by SIGSEGV +++
Speicherzugriffsfehler
root@HytGW02:/usr/local/src/DMRGateway#
73 Heiko, DL1BZ

**Comment by g4klx** [comment]
Try a new pull of DMR Gateway, it is reported to be fixed now.
    On Tuesday, 6 October 2020, 19:48:33 BST, Heiko <notifications@github.com> wrote:  
 
 


here is the strace:
mprotect(0x76bb1000, 4096, PROT_READ) = 0
munmap(0x76fb1000, 49217) = 0
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 5
connect(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.253.1")}, 16) = 0
poll([{fd=5, events=POLLOUT}], 1, 0) = 1 ([{fd=5, revents=POLLOUT}])
send(5, "D\f\1\0\0\1\0\0\0\0\0\0\5dmr02\5bzsax\2de\0\0\1\0\1", 32, MSG_NOSIGNAL) = 32
poll([{fd=5, events=POLLIN}], 1, 5000) = 1 ([{fd=5, revents=POLLIN}])
ioctl(5, FIONREAD, [48]) = 0
recvfrom(5, "D\f\201\200\0\1\0\1\0\0\0\0\5dmr02\5bzsax\2de\0\0\1\0\1"..., 1024, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.253.1")}, [28->16]) = 48
close(5) = 0
write(3, "I: 2020-10-06 18:45:40.548 DMR-L"..., 362) = 362
write(1, "I: 2020-10-06 18:45:40.548 DMR-L"..., 362I: 2020-10-06 18:45:40.548 DMR-LL: Original configuration message: DL1BZ 4313875004389875001501+51.1820+14.4317 000Bautzen Multi-Mode Repeater3http://none
20200606 MMDVM
) = 362

--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x20202020} ---
+++ killed by SIGSEGV +++
Speicherzugriffsfehler
root@HytGW02:/usr/local/src/DMRGateway#
73 Heiko, DL1BZ

**Comment by SA7BNT** [comment]
Thanks for fixing that. Working for me and online with the latest commit

73 Tim, SA7BNT

**Comment by dl1bz** [comment]
Perfect - confirm too now it works again. I'm just back from my job and check it. Thanks a lot for fixing.

73 Heiko, DL1BZ
